video_decoder:
  ros__parameters:
    local_broker_host: "127.0.0.1"
    match_broker_host: "192.168.12.1"
    broker_port: 3333
    topic: "CustomByteBlock"
    local_client_id: "sniper_receiver_local"
    mqtt_queue_size: 1000

    display: true
    display_scale: 2
    crosshair_offset_x: 0
    crosshair_offset_y: 0
    crosshair_width: 1

    stats_interval_s: 1.0
    debug_dump_enable: false
    debug_dump_every_n_frames: 20
    debug_dump_dir: "sniper_debug_imgs"
